"""Added JWT Storing Table

Revision ID: 647e9dadd7d6
Revises: 7083532c5cc4
Create Date: 2025-11-26 18:30:32.829158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '647e9dadd7d6'
down_revision: Union[str, Sequence[str], None] = '7083532c5cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jwt_tokens_id'), 'jwt_tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jwt_tokens_id'), table_name='jwt_tokens')
    op.drop_table('jwt_tokens')
    # ### end Alembic commands ###
