"""init fresh schema

Revision ID: ab32f287cf6d
Revises: 
Create Date: 2025-11-06 19:40:18.864690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab32f287cf6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_roles',
    sa.Column('role_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_roles_id'), 'additional_roles', ['id'], unique=True)
    op.create_table('admin',
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('employee',
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_account_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_branch_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_account_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_iban_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initial_base_salary', sa.Float(), nullable=False),
    sa.Column('current_base_salary', sa.Float(), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('fulltime_joining_date', sa.Date(), nullable=True),
    sa.Column('last_increment_date', sa.Date(), nullable=True),
    sa.Column('increment_amount', sa.Float(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('designation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cnic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('actual_date_of_birth', sa.Date(), nullable=True),
    sa.Column('hobbies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehicle_registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employee_employee_id'), 'employee', ['employee_id'], unique=False)
    op.create_table('employee_additional_roles',
    sa.Column('employee_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['additional_roles.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_additional_roles')
    op.drop_index(op.f('ix_employee_employee_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_additional_roles_id'), table_name='additional_roles')
    op.drop_table('additional_roles')
    # ### end Alembic commands ###
